version: "3"
services:
  influxdb:
    image: influxdb:1.7.10
    container_name: influxdb
    volumes:
      - "/var/data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"
      - "/var/data/influxdb/data:/var/lib/influxdb/data"
    ports:
      - "8086:8086"
    logging:
      driver: "json-file"
      options:
        max-size: "10240k"
        max-file: "10"
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin 
      - INFLUXDB_ADMIN_PASSWORD=changeme
    restart: unless-stopped
  grafana:
    image: grafana/grafana:6.7.1
    container_name: grafana
    links:
      - influxdb
    volumes:
      - "/var/data/grafana:/var/lib/grafana"
      - "/var/data/grafana/grafana.ini:/etc/grafana/grafana.ini"
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10240k"
        max-file: "10"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=changeme
    restart: unless-stopped
  nginx:
    image: nginx/nginx:latest
    build: ./nginx
    container_name: nginx
    links:
      - grafana
    volumes:
      - "/var/data/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "/var/data/certbot:/etc/letsencrypt"
    ports:
      - "443:443"
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10240k"
        max-file: "10"
    restart: unless-stopped
